# Generated by Django 4.1.3 on 2022-12-10 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member2',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='member2',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='member2',
            name='subject',
            field=models.CharField(max_length=50),
        ),
    ]
